function output_data_csv(fnFullCSV_summary, data, delimiter)

% Prepare some data/formatting parameters for writing the summary data
hdrNames = {'Sweep_Time', 'Baseline', 'CAP_Area', 'CAP_Area_Partial', ...
    'Peak_Time_1_Raw', 'Peak_Time_2_Raw', 'Peak_Height_1_Raw', ...
    'Peak_Height_2_Raw', 'Peak_Time_1_Fit', 'Peak_Time_2_Fit', ...
    'Peak_Time_3_Fit', 'Peak_Height_1_Fit', 'Peak_Height_2_Fit', ...
    'Peak_Height_3_Fit', 'Peak_Width_1_Fit', 'Peak_Width_2_Fit', ...
    'Peak_Width_3_Fit', 'Peak_Area_1_Fit', 'Peak_Area_2_Fit', ...
    'Peak_Area_3_Fit', 'Fit_Edge', 'Fit_RSquared_Adj', 'Fit_RMSE'};
hdrStrSummary = sprintf(['%s' delimiter], hdrNames{:});
strEdgesBL = sprintf(['Edge_Idx_Baseline' delimiter '%d', ...
    delimiter, '%d'], data.edges_baseline(1), data.edges_baseline(2));
strEdgesArea = sprintf(['Edge_Idx_Area' delimiter '%d', ...
    delimiter, '%d'], data.edges_area(1), data.edges_area(2));
dataMat = [data.time_sweeps, data.baseline, data.area_CAP, ...
    data.area_CAP_partial, data.peak_time_raw, data.peak_height_raw, ...
    data.peak_time_fit, data.peak_height_fit, data.peak_width_fit, ...
    data.peak_area_fit, data.edge_fit, data.fit_rsquared_adj, ...
    data.fit_rmse];

% Write the summary data to a csv file
dlmwrite(fnFullCSV_summary, strEdgesBL, 'delimiter', '');
dlmwrite(fnFullCSV_summary, strEdgesArea, '-append', 'delimiter', '');
dlmwrite(fnFullCSV_summary, hdrStrSummary(1:end-1), '-append', ...
    'delimiter', '');
dlmwrite(fnFullCSV_summary, dataMat, '-append', 'delimiter', delimiter, ...
    'precision', '%.5f');


end